<?php
        /**
	 * This file contains an array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * This file is generated by initconfigcache.php. Load initconfigcache.php at least once from your web server with your browser. 
	 * @package fcs-aggregator
	 */
	 
	/**
	 * An array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * Using the identifier for a resource the endPoint, name (back reference, the identifier),
	 * displayText (human intelligable name),
	 * type ("fcs.resource"), style (the stylesheet associated with the resource) and context 
	 * (for the x-context parameter can be determined). 
	 * @global array $configName
	 */
    $configName = array();

    $configName["lrp:abacus"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:abacus", "displayText" => "Abacus", "type" => "fcs.resource", "context" => "abacus");
    $configName["lrp:stb"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:stb", "displayText" => "Schnitzler Tagebuch", "type" => "fcs.resource", "context" => "stb");
    $configName["lrp:aac-names"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:aac-names", "displayText" => "AAC Namensdatenbank", "type" => "fcs.resource", "context" => "aac-names");
    $configName["lrp:vicav"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:vicav", "displayText" => "vicav", "type" => "fcs.resource", "context" => "vicav");
    $configName["lrp:dict-gate"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:dict-gate", "displayText" => "Dictionary Gate", "type" => "fcs.resource", "context" => "dict-gate");
    $configName["lrp:abacus"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:abacus", "displayText" => "Abacus", "type" => "fcs.resource", "context" => "abacus");
    $configName["lrp:stb"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:stb", "displayText" => "Schnitzler Tagebuch", "type" => "fcs.resource", "context" => "stb");
    $configName["lrp:aac-names"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:aac-names", "displayText" => "AAC Namensdatenbank", "type" => "fcs.resource", "context" => "aac-names");
    $configName["lrp:vicav"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:vicav", "displayText" => "vicav", "type" => "fcs.resource", "context" => "vicav");
    $configName["lrp:dict-gate"] = array("endPoint" => "http://clarin.aac.ac.at/exist/apps/cr-xq/lrp/fcs", "name" => "lrp:dict-gate", "displayText" => "Dictionary Gate", "type" => "fcs.resource", "context" => "dict-gate");
    
