<?php

/* 
 * The MIT License
 *
 * Copyright 2016 OEAW/ACDH.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

        /**
	 * This file contains an array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * This file is generated by initconfigcache.php. Load initconfigcache.php at least once from your web server with your browser. 
	 * @package fcs-aggregator
	 */
	 
	/**
	 * An array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * Using the identifier for a resource the endPoint, name (back reference, the identifier),
	 * displayText (human intelligable name),
	 * type ("fcs.resource"), style (the stylesheet associated with the resource) and context 
	 * (for the x-context parameter can be determined). 
	 * @global array $configName
	 */
    $configName = array();

	die("The file fcs.resource.config.php needs to be generated once! <br/> Either click <a href='initconfigcache.php'>here </a> or alternatively you can just remove it.");
    
?>
